const initialTravelData = [
    {
        id: 1,
        title: "Hiking the Inca Trail",
        content: "Embark on a breathtaking four-day trek through ancient trails to Machu Picchu, surrounded by stunning Andean peaks and lush cloud forests. The journey blends challenge with awe-inspiring ruins.",
        category: "Adventure",
        lat: -13.1631,
        lng: -72.5450,
        image: "images/image1.jpg",
        video: "",
        timestamp: new Date("2024-01-15").getTime(),
        season: "Spring",
        continent: "South America",
        country: "Peru",
        city: "Machu Picchu",
        author: "Alex Traveler",
        tags: ["hiking", "ancient ruins", "mountains"],
        likes: 0,
        comments: [],
        ratings: [],
        sponsored: false,
        affiliateLink: "https://example.com/affiliate-trekking-gear",
        availability: true,
        price: 1200,
        maxTravelers: 15
    },
    {
        id: 2,
        title: "Kyoto's Sacred Temples",
        content: "Immerse yourself in Japan's cultural heart, visiting the golden Kinkaku-ji, the vibrant Fushimi Inari with its thousand torii gates, and tranquil Zen gardens that inspire peace.",
        category: "Culture",
        lat: 35.0116,
        lng: 135.7681,
        image: "images/image2.jpg",
        video: "",
        timestamp: new Date("2024-02-20").getTime(),
        season: "Spring",
        continent: "Asia",
        country: "Japan",
        city: "Kyoto",
        author: "Maya Explorer",
        tags: ["temples", "culture", "zen"],
        likes: 0,
        comments: [],
        ratings: [],
        sponsored: false,
        affiliateLink: "https://example.com/affiliate-japan-tours",
        availability: true,
        price: 800,
        maxTravelers: 20
    },
    {
        id: 3,
        title: "Serengeti Safari Adventure",
        content: "Witness the great migration in Tanzania's vast savannas, where lions, elephants, and zebras roam under endless skies. A thrilling journey into the heart of the wild.",
        category: "Nature",
        lat: -2.3333,
        lng: 34.8333,
        image: "images/image3.jpg",
        video: "",
        timestamp: new Date("2024-03-10").getTime(),
        season: "Summer",
        continent: "Africa",
        country: "Tanzania",
        city: "Serengeti",
        author: "Sam Adventurer",
        tags: ["safari", "wildlife", "nature"],
        likes: 0,
        comments: [],
        ratings: [],
        sponsored: true,
        affiliateLink: "https://example.com/affiliate-safari-tours",
        availability: true,
        price: 1500,
        maxTravelers: 10
    },
    {
        id: 4,
        title: "Kayaking Lake Louise",
        content: "Paddle through the turquoise waters of Lake Louise, framed by the majestic Canadian Rockies. Every stroke reveals a postcard-perfect view of glaciers and peaks.",
        category: "Adventure",
        lat: 51.4170,
        lng: -116.2168,
        image: "images/image4.jpg",
        video: "",
        timestamp: new Date("2024-04-05").getTime(),
        season: "Summer",
        continent: "North America",
        country: "Canada",
        city: "Lake Louise",
        author: "Alex Traveler",
        tags: ["kayaking", "lakes", "mountains"],
        likes: 0,
        comments: [],
        ratings: [],
        sponsored: false,
        affiliateLink: "https://example.com/affiliate-kayak-rentals",
        availability: true,
        price: 900,
        maxTravelers: 12
    },
    {
        id: 5,
        title: "Venice Canal Journey",
        content: "Glide through Venice's historic canals, passing grand palazzos and hidden bridges. From St. Mark's Square to quiet corners, the city’s charm unfolds on this unforgettable tour.",
        category: "Culture",
        lat: 45.4408,
        lng: 12.3155,
        image: "images/image5.jpg",
        video: "",
        timestamp: new Date("2024-05-12").getTime(),
        season: "Spring",
        continent: "Europe",
        country: "Italy",
        city: "Venice",
        author: "Maya Explorer",
        tags: ["canals", "culture", "history"],
        likes: 0,
        comments: [],
        ratings: [],
        sponsored: false,
        affiliateLink: "https://example.com/affiliate-venice-tours",
        availability: true,
        price: 1100,
        maxTravelers: 18
    },
    {
        id: 6,
        title: "Chasing Iceland’s Northern Lights",
        content: "Hunt for the aurora borealis across Iceland’s dramatic landscapes, with starry skies, rugged cliffs, and geothermal pools creating a magical backdrop for this celestial show.",
        category: "Nature",
        lat: 64.9631,
        lng: -19.0208,
        image: "images/image6.jpg",
        video: "",
        timestamp: new Date("2024-06-18").getTime(),
        season: "Winter",
        continent: "Europe",
        country: "Iceland",
        city: "Jökulsárlón",
        author: "Sam Adventurer",
        tags: ["northern lights", "nature", "winter"],
        likes: 0,
        comments: [],
        ratings: [],
        sponsored: false,
        affiliateLink: "https://example.com/affiliate-iceland-tours",
        availability: true,
        price: 1300,
        maxTravelers: 15
    },
    {
        id: 7,
        title: "Trekking Patagonia",
        content: "Explore the rugged beauty of Patagonia, with jagged peaks, turquoise lakes, and glaciers. A trekker’s paradise in the wilds of South America.",
        category: "Adventure",
        lat: -50.7371,
        lng: -73.9872,
        image: "images/image7.jpg",
        video: "",
        timestamp: new Date("2024-07-22").getTime(),
        season: "Summer",
        continent: "South America",
        country: "Argentina",
        city: "Torres del Paine",
        author: "Alex Traveler",
        tags: ["trekking", "mountains", "nature"],
        likes: 0,
        comments: [],
        ratings: [],
        sponsored: false,
        affiliateLink: "https://example.com/affiliate-trekking-gear",
        availability: true,
        price: 1400,
        maxTravelers: 12
    },
    {
        id: 8,
        title: "Bali’s Rice Terraces",
        content: "Wander through Bali’s lush rice terraces, where vibrant green fields and ancient temples create a serene escape. A cultural and natural gem.",
        category: "Culture",
        lat: -8.3405,
        lng: 115.0920,
        image: "images/image8.jpg",
        video: "",
        timestamp: new Date("2024-08-30").getTime(),
        season: "Fall",
        continent: "Asia",
        country: "Indonesia",
        city: "Ubud",
        author: "Maya Explorer",
        tags: ["rice terraces", "culture", "nature"],
        likes: 0,
        comments: [],
        ratings: [],
        sponsored: false,
        affiliateLink: "https://example.com/affiliate-bali-tours",
        availability: true,
        price: 950,
        maxTravelers: 20
    }
];

// Export the data (if using modules)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = initialTravelData;
}